import { Product } from './store';

export const products: Product[] = [
  // Cashews
  {
    id: 'cashew-raw-250',
    name: 'Premium Raw Cashews',
    category: 'cashews',
    type: 'Raw',
    price: 12.99,
    image: '/placeholder.svg',
    description: 'Hand-selected whole cashews, naturally dried to preserve nutrients. Perfect for snacking or cooking.',
    nutritionalInfo: 'Per 100g: Calories 553, Protein 18g, Fat 44g, Carbs 30g, Fiber 3g',
    weight: '250g',
    inStock: true,
    rating: 4.9,
    reviews: 234,
  },
  {
    id: 'cashew-roasted-250',
    name: 'Honey Roasted Cashews',
    category: 'cashews',
    type: 'Roasted',
    price: 14.99,
    originalPrice: 17.99,
    image: '/placeholder.svg',
    description: 'Delicately roasted with pure honey for a sweet, crunchy treat. Irresistibly delicious.',
    nutritionalInfo: 'Per 100g: Calories 580, Protein 17g, Fat 42g, Carbs 35g, Fiber 2g',
    weight: '250g',
    inStock: true,
    rating: 4.8,
    reviews: 189,
  },
  {
    id: 'cashew-salted-500',
    name: 'Sea Salt Cashews',
    category: 'cashews',
    type: 'Salted',
    price: 22.99,
    image: '/placeholder.svg',
    description: 'Premium cashews lightly dusted with Himalayan pink sea salt. The perfect savory snack.',
    nutritionalInfo: 'Per 100g: Calories 560, Protein 18g, Fat 44g, Carbs 28g, Fiber 3g',
    weight: '500g',
    inStock: true,
    rating: 4.7,
    reviews: 156,
  },
  {
    id: 'cashew-spicy-250',
    name: 'Spiced Masala Cashews',
    category: 'cashews',
    type: 'Flavored',
    price: 15.99,
    image: '/placeholder.svg',
    description: 'Bold Indian spices coat these premium cashews for an exotic flavor experience.',
    nutritionalInfo: 'Per 100g: Calories 565, Protein 17g, Fat 43g, Carbs 32g, Fiber 3g',
    weight: '250g',
    inStock: true,
    rating: 4.6,
    reviews: 98,
  },
  {
    id: 'cashew-butter-350',
    name: 'Creamy Cashew Butter',
    category: 'cashews',
    type: 'Butter',
    price: 18.99,
    image: '/placeholder.svg',
    description: 'Stone-ground pure cashew butter with no additives. Silky smooth and naturally sweet.',
    nutritionalInfo: 'Per 100g: Calories 590, Protein 15g, Fat 50g, Carbs 22g, Fiber 2g',
    weight: '350g',
    inStock: true,
    rating: 4.9,
    reviews: 312,
  },
  {
    id: 'cashew-mixed-1kg',
    name: 'Premium Mixed Cashews',
    category: 'cashews',
    type: 'Mixed',
    price: 45.99,
    originalPrice: 52.99,
    image: '/placeholder.svg',
    description: 'Our signature blend of raw, roasted, and flavored cashews. Perfect variety pack.',
    nutritionalInfo: 'Per 100g: Calories 560, Protein 17g, Fat 43g, Carbs 30g, Fiber 3g',
    weight: '1kg',
    inStock: true,
    rating: 4.8,
    reviews: 445,
  },

  // Flours
  {
    id: 'flour-almond-500',
    name: 'Fine Almond Flour',
    category: 'flour',
    type: 'Almond',
    price: 16.99,
    image: '/placeholder.svg',
    description: 'Ultra-fine blanched almond flour, perfect for gluten-free baking. Makes tender cakes and cookies.',
    nutritionalInfo: 'Per 100g: Calories 590, Protein 21g, Fat 52g, Carbs 20g, Fiber 10g',
    weight: '500g',
    inStock: true,
    rating: 4.9,
    reviews: 567,
  },
  {
    id: 'flour-coconut-500',
    name: 'Organic Coconut Flour',
    category: 'flour',
    type: 'Coconut',
    price: 11.99,
    image: '/placeholder.svg',
    description: 'High-fiber, low-carb coconut flour from organic coconuts. Great for keto recipes.',
    nutritionalInfo: 'Per 100g: Calories 443, Protein 13g, Fat 14g, Carbs 60g, Fiber 41g',
    weight: '500g',
    inStock: true,
    rating: 4.7,
    reviews: 289,
  },
  {
    id: 'flour-wholewheat-1kg',
    name: 'Stone-Ground Whole Wheat',
    category: 'flour',
    type: 'Whole Wheat',
    price: 8.99,
    image: '/placeholder.svg',
    description: 'Traditional stone-ground whole wheat flour with all the natural goodness intact.',
    nutritionalInfo: 'Per 100g: Calories 340, Protein 13g, Fat 2g, Carbs 72g, Fiber 11g',
    weight: '1kg',
    inStock: true,
    rating: 4.8,
    reviews: 423,
  },
  {
    id: 'flour-allpurpose-2kg',
    name: 'Premium All-Purpose Flour',
    category: 'flour',
    type: 'All-Purpose',
    price: 9.99,
    image: '/placeholder.svg',
    description: 'Versatile all-purpose flour for everyday baking. Consistent results every time.',
    nutritionalInfo: 'Per 100g: Calories 364, Protein 10g, Fat 1g, Carbs 76g, Fiber 3g',
    weight: '2kg',
    inStock: true,
    rating: 4.6,
    reviews: 678,
  },
  {
    id: 'flour-oat-500',
    name: 'Gluten-Free Oat Flour',
    category: 'flour',
    type: 'Oat',
    price: 10.99,
    image: '/placeholder.svg',
    description: 'Certified gluten-free oat flour for nutritious baking. Adds wonderful texture.',
    nutritionalInfo: 'Per 100g: Calories 404, Protein 15g, Fat 9g, Carbs 66g, Fiber 10g',
    weight: '500g',
    inStock: true,
    rating: 4.7,
    reviews: 187,
  },
  {
    id: 'flour-chickpea-500',
    name: 'Organic Chickpea Flour',
    category: 'flour',
    type: 'Chickpea',
    price: 9.99,
    image: '/placeholder.svg',
    description: 'High-protein chickpea flour for savory dishes and gluten-free baking.',
    nutritionalInfo: 'Per 100g: Calories 387, Protein 22g, Fat 6g, Carbs 58g, Fiber 10g',
    weight: '500g',
    inStock: true,
    rating: 4.8,
    reviews: 234,
  },
];

export const getProductsByCategory = (category: 'cashews' | 'flour') =>
  products.filter((p) => p.category === category);

export const getProductById = (id: string) => products.find((p) => p.id === id);

export const getFeaturedProducts = () => products.filter((p) => p.rating >= 4.8).slice(0, 4);

export const getCashewTypes = () => [...new Set(products.filter(p => p.category === 'cashews').map(p => p.type))];

export const getFlourTypes = () => [...new Set(products.filter(p => p.category === 'flour').map(p => p.type))];
